apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-project
  template:
    metadata:
      labels:
        app: monitoring-project
    spec:
      containers:
        - name: monitoring-project
          image: monitoring-project:latest
          imagePullPolicy: IfNotPresent # 로컬 이미지 사용
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-project
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    app: my-project
